# Generated by Django 5.1.5 on 2025-02-07 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('location_description', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('social_security_affiliation', models.CharField(max_length=50)),
                ('days_lost', models.IntegerField(blank=True, null=True)),
                ('last_day_work', models.DateTimeField(blank=True, null=True)),
                ('worked_hours', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
