# Generated by Django 5.1.6 on 2025-02-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_accident_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
