# Generated by Django 5.1.6 on 2025-02-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch_accident_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='core.branch'),
        ),
    ]
