# Generated by Django 5.1.6 on 2025-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_accident_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='organizationId',
            field=models.CharField(max_length=255),
        ),
    ]
