# Generated by Django 5.1.6 on 2025-02-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_branch_organizationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='days_lost',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='last_day_work',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='social_security_affiliation',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='worked_hours',
        ),
    ]
