# Generated by Django 5.1.6 on 2025-02-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_accident_accidentpotential_accident_accidenttypeenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accidentPotential',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accidentTypeEnum',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
