# Generated by Django 5.1.6 on 2025-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_accident_accidentpotential_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='accidentPotential',
        ),
        migrations.AddField(
            model_name='accident',
            name='aaccidentPotential',
            field=models.CharField(blank=True, max_length=50, null=True, default='Baixo'),
        ),
    ]
