# Generated by Django 5.1.6 on 2025-02-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_accident_accidentpotential_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='aaccidentPotential',
            new_name='accidentPotential',
        ),
    ]
