# Generated by Django 5.1.6 on 2025-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_aaccidentpotential_accident_accidentpotential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accidentPotential',
            field=models.CharField(blank=True, default='Low', max_length=50, null=True),
        ),
    ]
