# Generated by Django 5.1.6 on 2025-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_accident_accidentpotential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accidentPotential',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accidentTypeEnum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
