# Generated by Django 5.1.6 on 2025-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_accident_accidentpotential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
