# Generated by Django 5.1.6 on 2025-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_accident_locomotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='daysLost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
