# Generated by Django 5.1.6 on 2025-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_accident_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='hasAbsence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
