# Generated by Django 5.1.6 on 2025-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_accident_hasabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='icd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
