# Generated by Django 5.1.6 on 2025-02-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_accident_icd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='icd',
            new_name='icd_code',
        ),
    ]
