# Generated by Django 5.1.6 on 2025-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_accident_comunicationtype_accident_timeworked'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='person_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='person_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
