# Generated by Django 5.1.6 on 2025-02-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_accident_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='hasAbsence',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='retired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
