# Generated by Django 5.1.6 on 2025-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_accident_hasabsence_alter_accident_retired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
