# Generated by Django 5.1.6 on 2025-02-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_accident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
